# Generated by Django 4.2 on 2023-04-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_onetimetoken_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_type',
            field=models.CharField(default='BLACK_AND_WHITE_SCREEN_800X480', max_length=200),
            preserve_default=False,
        ),
    ]
