# Generated by Django 4.2 on 2023-04-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_device_device_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='onetimetoken',
            name='user_device_ids',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
