# Generated by Django 4.0.6 on 2023-07-02 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_onetimetoken_user_device_ids'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Device',
            new_name='AuthorizedDevices',
        ),
    ]
