# Generated by Django 4.0.6 on 2023-07-02 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_device_authorizeddevices'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AuthorizedDevices',
            new_name='AuthorizedDevice',
        ),
    ]
