# Generated by Django 4.2 on 2023-07-08 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_authorizeddevices_authorizeddevice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthorizedDevice',
        ),
        migrations.DeleteModel(
            name='OneTimeToken',
        ),
    ]
