# Generated by Django 4.2 on 2023-07-08 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0008_delete_authorizeddevice_delete_onetimetoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppInstallation',
            fields=[
                ('installation_id', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('device_type', models.CharField(max_length=200)),
                ('is_vertically_oriented', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OneTimeToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installation_id', models.UUIDField(unique=True)),
                ('expiration_time', models.DateTimeField()),
                ('token', models.CharField(max_length=100)),
            ],
        ),
    ]
