# Generated by Django 4.2 on 2023-07-08 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appinstallation',
            name='device_type',
        ),
    ]
