# Docker-compose file for local development

version: '2'

services:
  redis:
    image: 'docker.io/bitnami/redis:6.0-debian-10'
    environment:
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
      - REDIS_AOF_ENABLED=no # Disable persistance
      - REDIS_PASSWORD=redis_password
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'

  postgresql:
    image: 'docker.io/bitnami/postgresql:12-debian-10'
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_DATABASE=image_gallery
      - POSTGRESQL_PASSWORD=image_gallery # user is: postgres

volumes:
  postgresql_data:
    driver: local

  redis_data:
    driver: local
