# Docker-compose file for local development

version: '2'

services:

  postgresql:
    image: 'docker.io/bitnami/postgresql:12-debian-10'
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_DATABASE=image_gallery
      - POSTGRESQL_PASSWORD=image_gallery # user is: postgres

volumes:
  postgresql_data:
    driver: local
